# Generated by Django 5.1.5 on 2025-03-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geraeteraum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fach', models.CharField(max_length=10)),
                ('fahrzeug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geraeteraeume', to='fahrzeuge.fahrzeug')),
            ],
        ),
    ]
