# Generated by Django 5.1.5 on 2025-01-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0004_rename_katgorie_geraet_kategorie'),
        ('pruefung', '0002_remove_pruefung_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkliste_Fragen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.CharField(max_length=200)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pruefung.art')),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geraete.kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Checkliste_Ergebnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort', models.BooleanField()),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pruefung.pruefung')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pruefung.checkliste_fragen')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pruefung', 'frage'), name='unique_pruefung_frage')],
            },
        ),
    ]
