# Generated by Django 5.1.5 on 2025-02-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruefung', '0004_alter_checkliste_ergebnis_bemerkung'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruefung',
            name='bestanden',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruefung',
            name='intervalle',
            field=models.PositiveIntegerField(default=12, help_text='Intervalle in Monaten'),
        ),
    ]
