# Generated by Django 5.1.5 on 2025-02-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0004_rename_katgorie_geraet_kategorie'),
        ('pruefung', '0006_rename_intervalle_pruefung_intervall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naechste_Pruefung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letzte_pruefung', models.DateField(blank=True, null=True)),
                ('naechse_pruefung', models.DateField(blank=True, null=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruefung.art')),
                ('geraet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geraete.geraet')),
            ],
            options={
                'unique_together': {('geraet', 'art')},
            },
        ),
    ]
