# Generated by Django 5.1.5 on 2025-02-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruefung', '0007_naechste_pruefung'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naechste_pruefung',
            old_name='naechse_pruefung',
            new_name='naechste_pruefung',
        ),
    ]
