# Generated by Django 5.1.5 on 2025-03-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruefung', '0008_rename_naechse_pruefung_naechste_pruefung_naechste_pruefung'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruefung',
            name='feueron',
            field=models.BooleanField(default=False),
        ),
    ]
