# Generated by Django 5.1.5 on 2025-03-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0012_alter_geraet_bezeichnung'),
        ('pruefung', '0009_pruefung_feueron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkliste_fragen',
            name='kategorie',
        ),
        migrations.AddField(
            model_name='checkliste_fragen',
            name='kategorie',
            field=models.ManyToManyField(to='geraete.kategorie'),
        ),
    ]
