# Generated by Django 5.1.5 on 2025-03-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0002_geraeteraum'),
        ('pruefung', '0010_remove_checkliste_fragen_kategorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fahrzeug_Fragen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Monat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monat', models.CharField(choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Dezember')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fahrzeug_Pruefung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(null=True)),
                ('pruefer', models.CharField(blank=True, max_length=50)),
                ('bestanden', models.BooleanField()),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('befund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pruefung.befund')),
                ('fahrzeug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fahrzeuge.fahrzeug')),
            ],
        ),
        migrations.CreateModel(
            name='Fahrzeug_Vorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fahrzeug', models.ManyToManyField(to='fahrzeuge.fahrzeug')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pruefung.fahrzeug_fragen')),
                ('monat', models.ManyToManyField(to='pruefung.monat')),
            ],
        ),
        migrations.CreateModel(
            name='Fahrzeug_Checkliste_Ergebnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort', models.BooleanField()),
                ('bemerkung', models.CharField(blank=True, max_length=200, null=True)),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pruefung.fahrzeug_fragen')),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pruefung.fahrzeug_pruefung')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pruefung', 'frage'), name='unique_pruefung_frage_fahrzeug')],
            },
        ),
    ]
