# Generated by Django 5.1.5 on 2025-01-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geraet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('identifikation', models.CharField(max_length=50, unique=True)),
                ('seriennummer', models.CharField(blank=True, max_length=50, null=True)),
                ('hersteller', models.CharField(blank=True, max_length=100, null=True)),
                ('kaufdatum', models.DateField(blank=True, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geraete.status')),
            ],
        ),
    ]
