# Generated by Django 5.1.5 on 2025-01-19 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='keine', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='geraet',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geraet',
            name='bemerkung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geraet',
            name='katgorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geraete.kategorie'),
        ),
    ]
