# Generated by Django 5.1.5 on 2025-01-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0002_kategorie_geraet_barcode_geraet_bemerkung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geraet',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
