# Generated by Django 5.1.5 on 2025-01-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0003_alter_geraet_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geraet',
            old_name='katgorie',
            new_name='kategorie',
        ),
    ]
