# Generated by Django 5.1.5 on 2025-03-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrzeuge', '0002_geraeteraum'),
        ('geraete', '0005_geraet_feueron_geraet_geraeteraum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geraet',
            name='geraeteraum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geraete', to='fahrzeuge.geraeteraum'),
        ),
    ]
