# Generated by Django 5.1.5 on 2025-03-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0006_alter_geraet_geraeteraum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geraet',
            name='feueron',
        ),
    ]
