# Generated by Django 5.1.5 on 2025-03-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0008_alter_geraet_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='geraet',
            name='infentartummer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
