# Generated by Django 5.1.5 on 2025-03-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0009_geraet_infentartummer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geraet',
            old_name='infentartummer',
            new_name='inventartummer',
        ),
    ]
