# Generated by Django 5.1.5 on 2025-03-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0010_rename_infentartummer_geraet_inventartummer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geraet',
            old_name='inventartummer',
            new_name='inventarnummer',
        ),
    ]
