# Generated by Django 5.1.5 on 2025-03-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geraete', '0011_rename_inventartummer_geraet_inventarnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geraet',
            name='bezeichnung',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
